server:
  port: 10011
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/jwt
    username: root
    password: 152033
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10010/eureka
    #registry-fetch-interval-seconds: 10
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: 127.0.0.1
    lease-expiration-duration-in-seconds: 10 #10秒不发送九过期

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 9000
#ribbon的超时时间
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000


ly:
  jwt:
    secret: jwt@jwt(@Auth>>!!)&hha%
    pubKeyPath: C:\\Users\\wuhen\\Desktop\\rsa.pub
    priKeyPath: C:\\Users\\wuhen\\Desktop\\rsa.pri
    expire: 30
    cookieName: j-cookie
    cookieMaxAge: -1
